import React from 'react'
import ProductListing from '../Components/ProductListing';
import { brands, getCategories } from '../services/ApiServices';


export const metadata = {
  title: "Product Listings",
  description: "Generated by create next app",
};

export default async function page() {

  var category = await getCategories();
  var brand = await brands();

  return (
    <>
      <ProductListing category={category} brand={brand}/>
    </>
  )
}
