import React from 'react'
import ProductListing from '../Components/ProductListing';


export const metadata = {
  title: "Product Listings",
  description: "Generated by create next app",
};

export default function page() {
  return (
    <>
      <ProductListing/>
    </>
  )
}
