import MainLayout from "./Components/Common/MainLayout";
import "./globals.css";

export const metadata = {
  title: " Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <MainLayout>

        {children}
        
      </MainLayout>
        
      
    </html>
  );
}
